# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

dist: trusty
sudo: required

language: cpp

compiler:
    - gcc

notifications:
    email:
        recipients:
            - su2code-dev@lists.stanford.edu
  
branches:
    only:
        - develop

env:
    global:
        CXXFLAGS="-O3 -Wall -Wextra -Wno-unused-parameter -Wno-empty-body -Wno-format-security" 
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER"
          TEST_SCRIPT=serial_regression.py

        # Parallel build and test
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER"
          TEST_SCRIPT=parallel_regression.py

        # Serial build and test for AD
        - CONFIGURE_COMMAND="./preconfigure.py --with-cc=gcc --with-cxx=g++ --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff"
          TEST_SCRIPT=serial_regression_AD.py

        # Parallel build and test for AD:
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff"
          TEST_SCRIPT=parallel_regression_AD.py

before_install:
    # Temporarily fixes Travis CI issue with paths for Python packages
    - export PATH=/usr/bin:$PATH

    # Install the necessary packages using apt-get with sudo
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential libopenmpi-dev swig python-numpy python-scipy python-mpi4py

    # to avoid interference with MPI
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX

install:
    # Configure, make, and install SU2
    - echo $TRAVIS_BUILD_DIR
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND
    - make -j 4
    - make install

    # Add environmental variables according to the configure step
    - export SU2_RUN=$TRAVIS_BUILD_DIR/bin
    - export SU2_HOME=$TRAVIS_BUILD_DIR
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN

before_script:
    # Get the test cases
    - git clone -b develop https://github.com/su2code/TestCases.git ./TestData
    - cp -R ./TestData/* ./TestCases/

    # Enter the SU2/TestCases/ directory, which is now ready to run
    - cd TestCases/

script:
    # Run the tests via the Python scripts
    - python $TEST_SCRIPT
